/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1-prealpha/spots/{spotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detailed spot info
         * @description Use this method to get spot
         */
        get: operations["GetSpot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1-prealpha/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves list of founded spots
         * @description Use this method to search spots
         */
        get: operations["SearchSpots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1-prealpha/sketches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates sketch of fitness geo-object
         * @description Use this method to create sketch (draft) you can customise later
         */
        post: operations["CreateSketch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1-prealpha/sketches/{sketchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves sketch of fitness geo-object
         * @description Use this method to get sketch (draft) you created previously
         */
        get: operations["GetSketch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ActivityTypes: "NordicSki" | "Workout" | "RollerSki" | "Biathlon";
        AddressDto: {
            country?: string | null;
            region?: string | null;
            settlement?: string | null;
            street?: string | null;
        };
        CreateSketchRequest: {
            activityTypes: components["schemas"]["ActivityTypes"][] | null;
            title: string | null;
            location: components["schemas"]["GeoLocationDto"];
            /** Format: double */
            altitude?: number | null;
        };
        GeoLocationDto: {
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
        };
        GetSpotResult: {
            /** Format: uuid */
            id: string;
            title: string | null;
            activities: components["schemas"]["ActivityTypes"][] | null;
            location?: components["schemas"]["GeoLocationDto"];
            address?: components["schemas"]["AddressDto"];
            description?: string | null;
        };
        HttpValidationProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        } & {
            [key: string]: unknown;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        SearchSpotResult: {
            /** Format: uuid */
            id?: string;
            location?: components["schemas"]["GeoLocationDto"];
            title?: string | null;
            address?: string | null;
            activities?: components["schemas"]["ActivityTypes"][] | null;
        };
        SearchSpotsResponse: {
            items?: components["schemas"]["SearchSpotResult"][] | null;
        };
        SketchDto: {
            /** Format: uuid */
            id?: string;
            title?: string | null;
            location?: components["schemas"]["GeoLocationDto"];
            activityTypes?: components["schemas"]["ActivityTypes"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetSpot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSpotResult"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SearchSpots: {
        parameters: {
            query: {
                q: string;
                activities?: components["schemas"]["ActivityTypes"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSpotsResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateSketch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSketchRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetSketch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sketchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SketchDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
